- shell: "ethermint --datadir /etc/ethermint unsafe_reset_all"
  when: "service == 'ethermint'"
  become_user: ethermint

- shell: "export BCHOME=/etc/basecoin ; basecoin unsafe_reset_all"
  when: "service == 'basecoin'"
  become_user: basecoin

- shell: "export TMHOME=/etc/basecoin/tendermint ; tendermint unsafe_reset_all"
  become_user: "{{service}}"

