---

- name: Install epel-release on CentOS/RedHat
  when: ansible_os_family == "RedHat"
  yum: "pkg=epel-release update_cache=yes state=latest"

- name: Install pip on CentOS/RedHat
  when: ansible_os_family == "RedHat"
  yum: "pkg={{item}} state=latest"
  with_items:
  - python2-pip
  - python-virtualenv

- name: Install toml 
  when: ansible_os_family == "RedHat"
  pip: name=toml

