---

- name: Update config.toml with json
  when: jsonconfig is defined
  tomlconfig: "dest='{{destination}}' json='{{jsonconfig}}' state={{(remove | default(false) | bool) | ternary('absent','present')}}"

- name: Update config.toml with toml
  when: tomlconfig is defined
  tomlconfig: "dest='{{destination}}' toml='{{tomlconfig}}' state={{(remove | default(false) | bool) | ternary('absent','present')}}"

