---
- name: update apt
  apt: >
    update_cache=yes
    cache_valid_time=3600
  when: ansible_os_family == "Debian"

- name: install deps (Ubuntu)
  apt: >
    pkg={{item}}
    state=installed
  with_items:
    - unzip
    - jq
  when: ansible_os_family == "Debian"

- name: install deps (RHEL)
  yum: >
    pkg={{item}}
    state=installed
  with_items:
    - unzip
    - jq
  when: ansible_os_family == "RedHat"

- name: create group
  group: >
    name={{tendermint_group}}
    state=present
    system=yes
  register: tendermint_group_created

- name: create user
  user: >
    home={{tendermint_home}}
    name={{tendermint_user}}
    group={{tendermint_group}}
    system=yes
  when: tendermint_group_created|changed

- name: create directory
  file: >
    path={{tendermint_home}}
    state=directory
    owner={{tendermint_user}}
    group={{tendermint_group}}
    mode=0755

# Check before creating log dir to prevent aggressively overwriting permissions
- name: check for log directory
  stat: >
    path={{ tendermint_log_file|dirname }}
  register: logdir

- name: create log directory if it does not exist
  file: >
    state=directory
    path={{ tendermint_log_file|dirname }}
    owner={{ tendermint_user }}
    group={{ tendermint_group }}
  when: not logdir.stat.exists

- name: touch the log file
  file: >
    state=touch
    path={{ tendermint_log_file }}
    owner={{ tendermint_user }}
    group={{ tendermint_group }}
  changed_when: false

- name: copy and unpack release binary
  when: tendermint_release_install
  unarchive: >
    src={{tendermint_download}}
    dest=/usr/local/bin
    remote_src=true
    mode=0755

- name: copy compiled binary
  when: not tendermint_release_install
  copy: >
    src={{tendermint_binary}}
    dest=/usr/local/bin
    mode=0755

- name: initialize tendermint
  command: "tendermint init"
  become: yes
  become_user: "{{tendermint_user}}"

- name: copy upstart script
  template: >
    src={{tendermint_upstart_template}}
    dest=/etc/init/tendermint.conf
    owner=root
    group=root
    mode=0644
  when: tendermint_use_upstart

- name: copy systemd script
  template: >
    src={{tendermint_systemd_template}}
    dest=/etc/systemd/system/tendermint.service
    owner=root
    group=root
    mode=0644
  when: tendermint_use_systemd
  notify:
    - reload systemd
