---

#variable "source" is required
#variable "destination" is required

- hosts: "{{ lookup('env','TF_VAR_TESTNET_NAME') }}:tag_Environment_{{ lookup('env','TF_VAR_TESTNET_NAME') | regex_replace('-','_') }}"
  gather_facts: no
  roles:
    - setfile

