name: Linter
on:
  push:
    branches:
      - v[0-9]+.[0-9]+.x-celestia
    paths:
      - "**.md"
      - "**.yml"
      - "**.yaml"
  pull_request:
    paths:
      - "**.md"
      - "**.yml"
      - "**.yaml"

jobs:
  build:
    name: Super linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0
      - name: Lint Code Base
        uses: docker://github/super-linter:v4
        env:
          LINTER_RULES_PATH: .
          VALIDATE_ALL_CODEBASE: true
          DEFAULT_BRANCH: v0.34.x-celestia
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_MD: true
          VALIDATE_OPENAPI: true
          VALIDATE_YAML: true

