name: Linter
on:
  push:
    branches:
      - v[0-9]+.[0-9]+.x-celestia
    paths:
      - "**.md"
      - "**.yml"
      - "**.yaml"
  pull_request:
    paths:
      - "**.md"
      - "**.yml"
      - "**.yaml"

jobs:
  build:
    name: Super linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Lint Code Base
        uses: docker://github/super-linter:v4
        env:
          LINTER_RULES_PATH: .
          VALIDATE_ALL_CODEBASE: true
          DEFAULT_BRANCH: v0.34.x-celestia
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_MD: true
          VALIDATE_OPENAPI: true
          VALIDATE_YAML: true

      - name: Check that all ADRs are linked in README
        working-directory: ./docs/architecture
        run: |
          find .  -regex '\./adr-[0-9][0-9][0-9].*.md$' -type f | xargs -I '{}' bash -c "grep -q {} README.md && true || (echo 'Missing ADR in README.md: {}'; (exit 1))"
